/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PooCaneta;

public class App {
    public static void main(String args[]) {
   Caneta caneta1 = new Caneta();
   caneta1.cor = "Verde";
   caneta1.ponta = 0.5f;
   caneta1.destampar();
   caneta1.rabiscar();
   caneta1.status();
   
   Caneta caneta2 = new Caneta();
   caneta2.modelo = "Kilometrica";
   caneta2.cor = "Azul";
      caneta2.tampar();
   caneta2.rabiscar();
   caneta2.status();
    }
       }
